### PR TITLE
Update stylelint to v9

### PR DESCRIPTION
**Pull request by satazor**
I will also update `stylelint-config-suitcss` after this gets merged and released.

### CODE REVIEW

**Comment by satazor** [comment]
@simonsmith do you know why the build is failing? Looks the same in master.

**Comment by simonsmith** [comment]
@satazor Not too sure. I'll take a look

**Comment by satazor** [comment]
@simonsmith It seems that the issue comes from the fact that we are caching stuff in `travis`. In my last commit, I've commented out the cache and it works.

Can I include this change in this PR?

**Comment by simonsmith** [comment]
@satazor Nice spot! Yeah go for it. Just delete it instead of commenting

**Comment by satazor** [comment]
Done, let the build pass again :)

**Comment by satazor** [comment]
Done, should be good.

Note that stylelint v9 no longer supports node v4. You may want to release a major because this can be considered a breaking change.

**Comment by simonsmith** [comment]
Released `3.0.0`. Thanks again @satazor

**Comment by satazor** [comment]
No problem! Follow up: https://github.com/suitcss/stylelint-config-suitcss/pull/34

**Pull request merged**
